### PR TITLE
[a11y] Small updates to header: skip links, navigation color contrast

### PR DESCRIPTION
**Pull request by iainnash**
Small header and site-wide a11y updates.

1. Added skip link
2. Updated header navigation color contrast
3. Added aria-labels to icon links in header
4. Added current page label in header navigation

### CODE REVIEW

**Comment by makermelissa** [comment]
@jwcooper are you still the correct person to review this?

Thanks

**Review by jwcooper — APPROVED** [review]

**Comment by makermelissa** [comment]
Thanks

**Comment by jwcooper** [comment]
Sorry! I missed this review request, looks good to me.

**Comment by makermelissa** [comment]
No worries, I miss review requests from time to time as well.

**Pull request merged**
