### PR TITLE
Patch 1 - updates

### PR DESCRIPTION
**Pull request by ITACAInnovation**
Changed link to Itaca Shop and updated pictures

### CODE REVIEW

**Comment by ITACAInnovation** [comment]
> Hi, it looks like you replaced the different sized images with 3 images of the same size. It would probably work better to leave the images as they were and update just the link. Thanks.

Hi Melissa,
alright thanks. We will provide correct picture for each size soon.
I will proceed only with the link update.

**Comment by ITACAInnovation** [comment]
Hi Melissa,
we updated the picture.
Ready for merging. Thanks

**Comment by makermelissa** [comment]
Would it be possible to make the images a little smaller? Here's a page that describes preparing the images. I just want to make sure your product looks great. Thanks. https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/preparing-the-images

**Comment by ITACAInnovation** [comment]
Ok, resized accordingly.
Thanks

**Pull request merged**
