### PR TITLE
Ohs2020 badge page

### PR DESCRIPTION
**Pull request by mwelling**
Add page and images for the OHS2020 badge.

### CODE REVIEW

**Comment by mwelling** [comment]
Per request on https://github.com/adafruit/circuitpython/pull/2528

**Comment by mwelling** [comment]
Sorry for taking so long I had to create the 3D renders because I don't have any board.

**Comment by mwelling** [comment]
@makermelissa Is that better?

**Comment by makermelissa** [comment]
Yes, thank you. I have one other small change is to request so that the images look their best on the site. Would you be able to resize the large and small images to 780x600 and 293x225? If not, I could do it in a separate PR. Thanks.

**Comment by mwelling** [comment]
Sure lemme take a look.

**Comment by mwelling** [comment]
Better?

**Comment by makermelissa** [comment]
Thank you!

**Pull request merged**
