### PR TITLE
Update to Ruby 3 and add RPI CP boards

### PR DESCRIPTION
**Pull request by tannewt**
Run the Jekyll build on pull_request as well to make sure it works

### CODE REVIEW

**Review by makermelissa — DISMISSED** [review]
Looks good. Thanks for updating the URLs.

**Comment by makermelissa** [comment]
FYI, looks like the build action is failing.

**Comment by jepler** [comment]
deploy should be guarded by an if: condition, then?

**Comment by tannewt** [comment]
I think the build step is doing fancier things than just building the site like fetching and committing new files. Could we split the data update from the build so that 1) we don't build on a schedule and 2) everyone can build on their branch.

**Comment by tannewt** [comment]
> I think the build step is doing fancier things than just building the site like fetching and committing new files. Could we split the data update from the build so that 1) we don't build on a schedule and 2) everyone can build on their branch.

I'm wrong about this. The build step was fine. I'll add a condition on the deploy.

**Comment by tannewt** [comment]
Build is green @makermelissa. I had to prevent the deploy when running on a PR.

**Review by makermelissa — APPROVED** [review]
Awesome, that works for me.

**Comment by makermelissa** [comment]
Not sure if you're waiting on Justin to also review.

**Review by jwcooper — APPROVED** [review]

**Pull request merged**
