### PR TITLE
Automated website update for release 5.0.0-beta.3

### PR DESCRIPTION
**Pull request by adafruit-blinka**
Automated website update for release 5.0.0-beta.3 by Blinka.

New boards:
* clue_nrf52840_express
* feather_mimxrt1062
* imxrt1010_evk
* feather_mimxrt1011

### CODE REVIEW

**Comment by ladyada** [comment]
@makermelissa @arturo182 we'll need content for downloads page :)

**Comment by makermelissa** [comment]
CLUE is already there (though the image could be updated), so it looks like we just need the IMX boards.

**Comment by makermelissa** [comment]
I found feather images (and a bit of info) here: https://twitter.com/arturo182/status/1199841134253682690
I haven't located anything for imxrt1010_evk yet...

**Comment by ladyada** [comment]
https://www.nxp.com/design/development-boards/i.mx-evaluation-and-development-boards/i.mx-rt1010-evaluation-kit:MIMXRT1010-EVK

**Comment by makermelissa** [comment]
thx!

**Comment by arturo182** [comment]
You work too fast, I was planning to do it :sweat_smile:

**Comment by tannewt** [comment]
@arturo182 please PR the new images when you have a chance!

**Comment by makermelissa** [comment]
@arturo182, you can update them with additional info.

**Pull request merged**
