### PR TITLE
Added CircuitBrains Deluxe and Basic boards

### PR DESCRIPTION
**Pull request by neubauek**
Requesting to add my CircuitBrains Deluxe and Basic boards.

### CODE REVIEW

**Comment by ladyada** [comment]
nice! thanks :)

**Comment by ladyada** [comment]
@neubauek looks great - needs another small PR please change the 'names' here to
`circuitbrains_basic_m0`
and
`circuitbrains_deluxe_m4/`
to match the buckets https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin

**Comment by neubauek** [comment]
Thanks! @ladyada do you mean the `board_id` field?

**Comment by ladyada** [comment]
yes!

**Pull request merged**
