### PR TITLE
Add E-Fidget board

### PR DESCRIPTION
**Pull request by 2231puppy**
This board was just merged in to CircuitPython, so here's the circuitpython.org page!

[Pull Request](https://github.com/adafruit/circuitpython/pull/7412)

Is a render OK for the board pictures? Let me know if changes are needed.

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi, thanks for adding. Using a render is fine, though a photo is preferable if you have one. Is it possible to clean up the black bars on the top and bottom of the image?

**Comment by 2231puppy** [comment]
I think I'll swap in real images. I just used the render because it looks cleaner.

**Comment by 2231puppy** [comment]
@makermelissa I switched the renders for real photos, and they look good on my end. Is the quality OK? It's the best I have on hand right now.

**Review by makermelissa — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
