### PR TITLE
Add new board: Cytron Maker Zero SAMD21

### PR DESCRIPTION
**Pull request by mlhakimz**
Hello, can you help to add this new board?

[https://my.cytron.io/p-maker-zero-samd21](https://my.cytron.io/p-maker-zero-samd21)

Thanks.

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Hi, could you add the family field in the top section. It looks like for this one, the value should be **atmel-samd**. I literally just got done updating the guide with this information: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/adding-to-downloads

Thanks

**Comment by makermelissa** [comment]
Also, it looks like you have some non-standard features. You can check the same guide page for a list of valid values. Thanks.

**Comment by makermelissa** [comment]
Note: This is also waiting on https://github.com/adafruit/circuitpython/pull/6432 to be merged.

**Comment by mlhakimz** [comment]
@makermelissa Thanks for reviewing. I've added the family field & the bootloader_id (currently waiting for [adafruit/uf2-samdx1#190](https://github.com/adafruit/uf2-samdx1/pull/190)). I also modified the technical specifications to the correct format.

**Review by makermelissa — APPROVED** [review]
Awesome. Looks good. Just waiting on https://github.com/adafruit/circuitpython/pull/6432 before merging.

**Comment by dhalbert** [comment]
I merged #6432, so merging this. Thanks @makermelissa.

**Pull request merged**
