### PR TITLE
add the Open Book board

### PR DESCRIPTION
**Pull request by joeycastillo**

### CODE REVIEW

**Comment by theacodes** [comment]
Huzzah! Congrats! ✨

**Comment by theacodes** [comment]
& it's up: https://circuitpython.org/board/openbook_m4/ :)

**Comment by ladyada** [comment]
nice!

**Comment by ladyada** [comment]
thanks for the review @theacodes

**Comment by joeycastillo** [comment]
thanks, y'all! 😄

**Pull request merged**
