### PR TITLE
Adding seperate boards for PyCubed v04 and v05

### PR DESCRIPTION
**Pull request by maholli**
This PR aligns circuitpython-org resources to pending changes on main circuitpython.

## ❗ Important

Please don't merge this RP until https://github.com/adafruit/circuitpython/pull/5302 is approved and merged. Thanks! 🙂

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Blocking until the CP PR is merged in.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please don't change the image file names of the existing board. That way they should all match board ID. It's ok to change title and name.

**Comment by maholli** [comment]
> 
> 
> Please don't change the image file names of the existing board. That way they should all match board ID. It's ok to change title and name.

Fixed 😄

**Comment by tannewt** [comment]
You need to change the actual files back too.

**Comment by maholli** [comment]
> 
> 
> You need to change the actual files back too.

Darn! VERY sorry for the oversight & making you catch that. Incorrectly assumed the build check would catch it.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
