### PR TITLE
Add more Blinka info

### PR DESCRIPTION
**Pull request by tannewt**
@jwcooper Mind polishing this up before committing? It may need a few more words and new images. Thanks!

### CODE REVIEW

**Comment by tannewt** [comment]
cc @ptorrone

**Comment by jwcooper** [comment]
@tannewt Just seeing this now. Can we merge and deploy this so @tylerdcooper can review how it looks?

I can update it based on his redlines/feedback. The content looks good, just needs the new images as far as I can tell.

**Comment by tannewt** [comment]
I'd rather not merge as-is because of the duplicated images. Here is the homepage:

Screenshot_2020-11-17 CircuitPython

**Comment by jwcooper** [comment]
Makes sense, @tylerdcooper is working on getting a rpi image for that new spot.

**Comment by tylerdcooper** [comment]
Lets just use this transparent background png of the Pi 3 for that image for now. Not the same dimensions, but it should work fine. @tannewt Let me know if you had something else in mind.

rpi_3

**Comment by makermelissa** [comment]
Were you intending the Raspberry Pi image to go in place of the duplicate pinball machine image or the duplicate python logo?

**Comment by makermelissa** [comment]
I'm guessing this is to replace the logo due to the size and transparency. If so, what would you like in place of the pinball machine image?

**Comment by makermelissa** [comment]
Never mind, I just saw the HTML comments. Sensors. Got it. 👍

**Comment by makermelissa** [comment]
Do we have an image of a bunch of sensors? I couldn't find anything on Flickr or learn.

**Comment by tannewt** [comment]
@CollinCunningham may have an image with a bunch of sensors

**Comment by makermelissa** [comment]
Closing in favor of #614.

**Pull request closed without merging**
