### PR TITLE
Add MagTag 2.9 plus update ESP32S2 Metro

### PR DESCRIPTION
**Pull request by makermelissa**
This is one I'm glad I tested before submitting. The quote in the 2.9" was a curve ball.

### CODE REVIEW

**Review by FoamyGuy — APPROVED** [review]
I built this locally and checked served pages. Both changes look good to me. I see MagTag in the list of downloads now. and the Metro ESP32 S2 has a new image and no longer says coming soon.

**Comment by makermelissa** [comment]
Thanks for reviewing @FoamyGuy

**Comment by ladyada** [comment]
@kattni check in a few mins!

**Comment by kattni** [comment]
I somehow missed this. Verified both work.

**Pull request merged**
