### PR TITLE
Adding Targett S2-MCB information

### PR DESCRIPTION
**Pull request by Targett363**
After my enforced time away from my computer, I'm back and updating things.
Here's hoping that 3am brain still works!

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Thanks for adding. Could you please resize the images to better match the other images on the site? See https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/preparing-the-images for some guidelines.

**Comment by Targett363** [comment]
I’m taking better shots tomorrow anyway, thanks for the learn guide heads up. Reading and photography for me tomorrow.

**Comment by makermelissa** [comment]
Thanks, that sounds good. :)

**Review by makermelissa — APPROVED** [review]
Looks great! Thanks!

**Comment by Targett363** [comment]
Many thanks MakerMelissa and all the AdaFolks!

**Pull request merged**
