### PR TITLE
Add maker feather aiot s3

### PR DESCRIPTION
**Pull request by Hz-Goh**
Hi,

I am from Cytron technologies. Please help to add this new board - Maker Feather AIoT S3

Thanks.

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Hi, thanks for adding. It looks like it's not passing the checks because you have some non-standard features:
AI and IoT. We generally try and keep the features narrowed down to a list that several boards share.

**Comment by Hz-Goh** [comment]
Hi, sorry for the inconveniences, I have made changes on the errors. Please me to add the board again. Thanks

**Review by makermelissa — APPROVED** [review]
Thanks, looks good.

**Comment by Hz-Goh** [comment]
Thanks

**Pull request merged**
