### PR TITLE
Automated website update for release 5.0.0-rc.0

### PR DESCRIPTION
**Pull request by adafruit-blinka**
Automated website update for release 5.0.0-rc.0 by Blinka.

New boards:
* arduino_nano_33_iot
* pycubed
* circuitbrains_basic_m0
* circuitbrains_deluxe_m4
* sparkfun_samd51_thing_plus
* espruino_wifi
* stm32f4_discovery
* espruino_pico
* feather_m7_1011

### CODE REVIEW

**Comment by ladyada** [comment]
kk @makermelissa we have 4 unknown boards (maybe renames, maybe new?) wanna try addin' em in or wrangling the designers :D

**Comment by makermelissa** [comment]
Sure!

**Comment by makermelissa** [comment]
Ok, 4 unknowns are:
arduino_nano_33_iot
pycubed
stm32f4_discovery (I'm guessing this is stm32f407vg_discovery since we have like 4 different stm32f4_discovery boards)
feather_m7_1011

**Comment by ladyada** [comment]
@hierophect what is 'stm32f4_discovery' and can we rename it to be more descriptive :)

**Comment by hierophect** [comment]
@ladyada the STM32F4_discovery's annoying name strikes again! Yes, the STM32F4 Discovery is the STM32F407VG board, I think it was the first one they made, so it doesn't actually describe what chip it has on it even in on the ST page, you have to look at the specs. Opinion is divided on whether it should be renamed the F407 Discovery - TinyUSB calls it the stm32f407disco, Zephyr and Micropython call it just the stm32f4_disco and STM32F4DISCO, respectively. 

@tannewt you were leaning toward the official name, last time I checked. Any reconsideration? Personally I'd vouch for the rename since I've seen this conversation happen like 3 times already and the rename would avoid such confusion - the Discovery boards have such loose branding anyway, hence the different names across MBED, Zephyr, Micropython, etc already.

**Comment by makermelissa** [comment]
I'm fine with either really, but I just need to know which direction to go on the STM32 board. @ladyada, do you have any pics/info on the feather_m7_1011? I found stuff for pycubed and the arduino already.

**Comment by arturo182** [comment]
The M7 1011 Feather arrived at Adafruit office today so I'd expect official photos to appear soon. If you want something even sooner, you can use this: https://pbs.twimg.com/media/ERAQFsPW4AgvItW?format=jpg&name=large

**Comment by ladyada** [comment]
yep we'll get pix next week!

**Comment by makermelissa** [comment]
Thanks for the reminder, I'll grab the diagonal one from https://twitter.com/arturo182/status/1229500410664280064

**Comment by makermelissa** [comment]
Ok, unless I hear differently, I'm just going to rename the stm32f407vg_discovery board on here to stm32f4_discovery since it's easier than renaming in CP.

**Comment by hierophect** [comment]
@makermelissa is that something we can change later?

**Comment by makermelissa** [comment]
Yes

**Comment by makermelissa** [comment]
I was able to set the title to STM32F407 Discovery kit, so I guess it doesn't need to be a 1:1 match.

**Comment by tannewt** [comment]
@hierophect Sorry I just saw this. I do like the vague stm32f4 since it matches the manufacturer name. I think that is where it settled anyway.

**Comment by hierophect** [comment]
@tannewt all good, this strikes me as a support/docs issue so I don't have a strong opinion either way. I'd say chat directly with ladyada or makermelissa if it comes up again.

**Pull request merged**
