### PR TITLE
Added board - BLE-SS Dev Board Multi Sensor

### PR DESCRIPTION
**Pull request by arms22**
Hello.
I have added a new board.
Please review and merge.

### CODE REVIEW

**Comment by ladyada** [comment]
im reviewing and will get to on tuesday :)

**Comment by arms22** [comment]
Hello.
How did your review of this PR go?

**Review by tannewt — APPROVED** [review]
Sorry for the delay! Looks great!

**Comment by arms22** [comment]
hi tannewt.
Thank you!

**Pull request merged**
