### PR TITLE
Add LilyGo T-Display RP2040

### PR DESCRIPTION
**Pull request by fabaff**
Depends on https://github.com/adafruit/circuitpython/pull/6037

### CODE REVIEW

**Comment by dhalbert** [comment]
Making this a draft so it's not merged before https://github.com/adafruit/circuitpython/pull/6037 is done.

**Comment by makermelissa** [comment]
I noticed that the board_id and board filename don't match the actual board's id: lilygo_t_display_rp2040. This must be older than the additional checks we added in last year or it likely wouldn't have passed.

**Comment by makermelissa** [comment]
I pushed the requested updates by @rcarteraz as this is pretty stale. I also fixed some other spelling issues.

**Review by makermelissa — DISMISSED** [review]
Looks good with the fixes I pushed.

**Comment by makermelissa** [comment]
Wait no. Apparently it includes a year's worth of fixes. Need to rebase...

**Comment by makermelissa** [comment]
Rebase successful.

**Review by makermelissa — APPROVED** [review]
Ok, now it looks good.

**Pull request merged**
