### PR TITLE
Add Deneyap Development Boards

### PR DESCRIPTION
**Pull request by DogushC**
Add Deneyap Development Boards' info and images.

List of Deneyap Development Boards

- Deneyap Kart
- Deneyap Mini
- Deneyap Kart 1A
- Deneyap Kart G
- Deneyap Mini v2
- Deneyap Kart 1A v2

### CODE REVIEW

**Comment by tannewt** [comment]
Do you have a PR to CircuitPython itself for support?

**Comment by DogushC** [comment]
> Do you have a PR to CircuitPython itself for support?

I would like to add a our development board to the circuitpython.org website.

**Comment by jepler** [comment]
The boards section on circuitpython.org is only for boards that have support in https://github.com/adafruit/circuitpython -- it does not list boards that are supported only in micropython, or only in a fork of circuitpython.

**Comment by DogushC** [comment]
> The boards section on circuitpython.org is only for boards that have support in https://github.com/adafruit/circuitpython -- it does not list boards that are supported only in micropython, or only in a fork of circuitpython.

That's right. If the PR will be merged, our boards will be listed in https://github.com/adafruit/circuitpython... 
I followed the instruction in https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Comment by tannewt** [comment]
You'll need to do this first: https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython

**Comment by DogushC** [comment]
> You'll need to do this first: https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython

I see. Thanks.

**Comment by dhalbert** [comment]
I added a sentence to the https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website guide to say that adding the board to CircuitPython is a prerequisite.

**Comment by DogushC** [comment]
> I added a sentence to the https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website guide to say that adding the board to CircuitPython is a prerequisite.

Now we are working on adding our boards in CircuitPython repo. Will you close the PR or wait it until its done?

**Comment by makermelissa** [comment]
> Now we are working on adding our boards in CircuitPython repo. Will you close the PR or wait it until its done?

I'll convert it to a draft PR and you can update it and fix the failing checks when you're ready.

**Comment by DogushC** [comment]
> It looks like it's failing because your descriptions have features that are different than out current standard set of feature filters. See https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/adding-to-downloads for more info.

Done.

**Review by makermelissa — APPROVED** [review]
Looks great. Thanks.

**Pull request merged**
