### PR TITLE
Wrong information how to enter UF2 bootloader

### PR DESCRIPTION
**Pull request by mikaelsundin**
Wrong infromation how to enter UF2 bootloader.

No propose changes button exist for "Install, Repair, or Update UF2 Bootloader" section on page 
https://circuitpython.org/board/lolin_s2_mini/

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Ok, so the problem with this approach is that the boot loader section will still be there, which could be confusing (See https://github.com/adafruit/circuitpython-org/blob/main/_includes/download/board.html#L171-L248). Also, since I don't have the Lolin S2 Mini, I can't verify that these steps are different, so I'll have to take your word on it. You could always remove the value from bootloader_id to hide the section, but the downloadable file wouldn't be there.

I'm wondering if there may be a better approach to this like specifying a `hide_bootloader_instructions` in https://raw.githubusercontent.com/adafruit/circuitpython-org/main/_board/lolin_s2_mini.md and then checking for that. 

Please let me know your thoughts on that based on your comfort level with making changes like this.

**Comment by Neradoc** [comment]
> Ok, so the problem with this approach is that the boot loader section will still be there, which could be confusing (See https://github.com/adafruit/circuitpython-org/blob/main/_includes/download/board.html#L171-L248). 

Note that this is only one paragraph, the one added in #1005 

> Also, since I don't have the Lolin S2 Mini, I can't verify that these steps are different, so I'll have to take your word on it.

These are the generic instructions for any ESP32-Sx board. The instructions written as they are now are specifically for Adafruit boards, as I mentioned: https://github.com/adafruit/circuitpython-org/pull/1005#issuecomment-1196602500
We need a better solution than editing the board's file. Dan mentioned a general-purpose Learn Guide page for detailed instructions.

**Comment by mikaelsundin** [comment]
The information is available in Adafruit Tinyuf2 gitrepo.

https://github.com/adafruit/tinyuf2/blob/master/ports/espressif/boards/lolin_s2_mini/board.h
Line 31

> // Enter UF2 mode if GPIO is pressed while 2nd stage bootloader indicator
> // is on e.g RGB = Purple. If it is GPIO0, user should not hold this while
> // reset since that will instead run the 1st stage ROM bootloader
> #define PIN_BUTTON_UF2        0

**Comment by makermelissa** [comment]
> > Ok, so the problem with this approach is that the boot loader section will still be there, which could be confusing (See https://github.com/adafruit/circuitpython-org/blob/main/_includes/download/board.html#L171-L248).
> 
> Note that this is only one paragraph, the one added in #1005
> 
> > Also, since I don't have the Lolin S2 Mini, I can't verify that these steps are different, so I'll have to take your word on it.
> 
> These are the generic instructions for any ESP32-Sx board. The instructions written as they are now are specifically for Adafruit boards, as I mentioned: [#1005 (comment)](https://github.com/adafruit/circuitpython-org/pull/1005#issuecomment-1196602500) We need a better solution than editing the board's file. Dan mentioned a general-purpose Learn Guide page for detailed instructions.

Ok, I can go ahead and approve/merge this for now with the understanding that this will be better addressed later.

**Review by makermelissa — APPROVED** [review]
After a little discussion, this is fine.

**Pull request merged**
