### PR TITLE
Add Datanoise PicoADK v2.

### PR DESCRIPTION
**Pull request by DatanoiseTV**

### CODE REVIEW

**Review by DatanoiseTV — COMMENTED** [review]
Remove wrong features, fix typos and name.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add images too.

**Comment by DatanoiseTV** [comment]
> Please add images too.
Thank you for the hint. Done.

**Comment by tannewt** [comment]
The images are the wrong dimensions: https://github.com/adafruit/circuitpython-org/actions/runs/11271484404/job/31344389534?pr=1487

**Comment by FoamyGuy** [comment]
This device has been added with #1502.

**Pull request closed without merging**
