### PR TITLE
Automated website update for release 5.0.0-beta.2

### PR DESCRIPTION
**Pull request by adafruit-blinka**
Automated website update for release 5.0.0-beta.2 by Blinka.

New boards:
* teknikio_bluebird
* xinabox_cc03
* xinabox_cs11
* stm32f411ce_blackpill

### CODE REVIEW

**Comment by makermelissa** [comment]
Do we have any info on stm32f411ce_blackpill? It will appear as an unknown board until added and it would be nice to have something.

**Comment by tannewt** [comment]
@hierophect and @ladyada know the details I think.

**Comment by ladyada** [comment]
pix here
https://www.flickr.com/search/?text=stm32f411

**Comment by hierophect** [comment]
@makermelissa what information do you need? It's a little generic board off AliExpress, seller name is literally "All_goods_are_free_shipping", so not a lot of manufacturer info to go off. 

https://www.aliexpress.com/item/4000068998794.html

You can see the PR here:
https://github.com/adafruit/circuitpython/pull/2361

**Comment by hierophect** [comment]
The name isn't literally "Blackpill" either, I just chose it since it's similar in layout and appearance to the nameless black F103 boards on AliExpress, which get called "blackpills" alongside the more famous $2 "bluepills". I'm totally open to suggestions if anyone has a better idea for an official title.

**Comment by makermelissa** [comment]
Thanks @ladyada and @hierophect, that should be enough information.

**Comment by makermelissa** [comment]
Whichever name is fine with me as long as it isn't "unknown".

**Comment by ladyada** [comment]
yeah its best to recognize these sorta boards by photo >.<

**Pull request merged**
