### PR TITLE
Update adafruit_feather_rp2040.md

### PR DESCRIPTION
**Pull request by sctv**
Updated that rp2040 based feather can use an Arduino core.  Welcome feedback on how to phrase it better.
A similar line should be included in all rp2040 based boards. 
Thanks.

### CODE REVIEW

**Comment by jepler** [comment]
Thanks, this would be a good update to make.

Because we like the text for Adafruit products to match what's in the shop, I've raised this issue internally. I'll get back to you about this, and if I don't you should feel free to ping me about it in a few days.

**Review by makermelissa — CHANGES_REQUESTED** [review]
It looks like you have some duplicate text in there. Want to fix it?

**Comment by sctv** [comment]
@jepler @makermelissa will sync this description up with the product page [rp2040 feather](https://www.adafruit.com/product/4884) tomorrow. Still getting my head around git/hub/branches/pr's etc.
thanks for your patience. Have allowed edits by maintainers on patch-2.

**Review by makermelissa — APPROVED** [review]
Looks good. Thanks for making the changes. Also we prefer to assist others in learning how to use GitHub instead of just doing it for them.

**Pull request merged**
