### PR TITLE
Added board page for new Pimoroni Motor 2040

### PR DESCRIPTION
**Pull request by ZodiusInfuser**
This will be launching today (fingers crossed), and already has the CircuitPython definition merged into the main release.

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
On hold, as we investigate something.

**Comment by makermelissa** [comment]
Since this board is showing up as an unknown board, I'm going to hide the board for now which requires a file in place. Feel free to replace it if there's a merge conflict.

**Comment by ZodiusInfuser** [comment]
Ah okay, I did not realise. Thank you.

**Comment by ZodiusInfuser** [comment]
Apologies for the delay. Board had to go through a revision, so added new images and updated the description. This PR is ready to go again @makermelissa

**Review by makermelissa — APPROVED** [review]
Awesome. Thanks for getting back to this.

**Pull request merged**
