### PR TITLE
Update adafruit_metro_esp32s2.md

### PR DESCRIPTION
**Pull request by jerryneedell**
correct PSRAM size - Wrover Module has 2Mbyte PSRAM -- was listed as 8.

### CODE REVIEW

**Comment by makermelissa** [comment]
Where'd you get the size info? The description came from https://www.adafruit.com/product/4775, so maybe the product page needs to be updated too?

**Comment by ladyada** [comment]
its 2 MB of PSRAM, 4 MB of flash - just checked espressif site

**Review by makermelissa — APPROVED** [review]

**Comment by jerryneedell** [comment]
> Where'd you get the size info? The description came from https://www.adafruit.com/product/4775, so maybe the product page needs to be updated too?

https://www.adafruit.com/product/4693
and
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/hw-reference/esp32s2/user-guide-saola-1-v1.2.html

**Comment by makermelissa** [comment]
Thanks @jerryneedell

**Pull request merged**
