### PR TITLE
Add initial RP2350 boards

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by arturo182** [comment]
I was just about to add my Stamps, thank you!

Glad I checked first :)

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
lgtm thanx!!!

**Comment by tannewt** [comment]
> I was just about to add my Stamps, thank you!
> 
> Glad I checked first :)

No problem! Please make a PR to pid.codes for the USB PIDs you added.

**Comment by arturo182** [comment]
Yes, I am planning to do that but need to wait for the Stamps to go on sale, that's when I publish the HW designs and can qualify for a PID :)

**Comment by makermelissa** [comment]
Thanks for adding this Scott.

**Pull request merged**
