### PR TITLE
fix files.json trailing commas

### PR DESCRIPTION
**Pull request by Neradoc**
Fixes error on `json.load()`.

### CODE REVIEW

**Review by makermelissa — COMMENTED** [review]
Thanks for fixing this. Since this file is auto-generated, is this likely to be an issue in the future?

**Review by jepler — APPROVED** [review]
Spot checked and the changes look okay

**Comment by dhalbert** [comment]
> Thanks for fixing this. Since this file is auto-generated, is this likely to be an issue in the future?

This was my fault. It doesn't normally contain trailing commas. I had to edit it by hand due to https://github.com/adafruit/circuitpython/issues/4470

**Review by dhalbert — COMMENTED** [review]
:+1:

**Pull request merged**
