### PR TITLE
Add more download options. 

### PR DESCRIPTION
**Pull request by tannewt**
Add stable vs unstable coloring. Also add S3 and GitHub links for
leading edge builds and past releases respectively.

Lastly, import 3.1.2 as a one off stable release using a hacked up
script.

Screen Shot 2019-03-11 at 7 04 59 PM

### CODE REVIEW

**Comment by tylerdcooper** [comment]
54169604-9e82c500-4430-11e9-94e9-1f24a1cce8eb

**Comment by tannewt** [comment]
I've updated the colors as asked but am not comfortable with sizing and positioning CSS. @jwcooper would you mind following up with positioning fixes? Thanks!

Screen Shot 2019-03-12 at 11 10 28 AM

**Comment by jwcooper** [comment]
Yup! I'll be able to dig into it this afternoon (after meeting) yet.

**Comment by tannewt** [comment]
Thank you!

**Pull request merged**
