### PR TITLE
Add cezerio dev ESP32C6

### PR DESCRIPTION
**Pull request by DogushC**

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@DogushC  Are there any photographs available of the real device? No other boards use a rendered pinout for the image here, photographs are preferred. 

The link listed in the description under purchase (https://cezerio.com/cezerio_dev_esp32c6) leads to a page with a "buy with paypal" button, but that button appears to be a link pointing to the same page that you're already on. Is it actually possible to purchase this device? 

On the home page of of cezerio.com there is a row of product listings, one of them is this devices name and it does contain a photo, but the photo seems to be of a different device made by the company Denyapkart. Is that company or device somehow related to the cezerio esp32c6 that is being added here?

**Comment by DogushC** [comment]
@FoamyGuy Manufacturing process has been still continuing so i have not had "cezerio dev ESP32C6" yet. I will get it in 3 weeks; then i will add photographs instead of images.
We are developer&manufacturer of electonics development boards and modules under "Deneyapkart" brand.
"cezerio" is a new brand and its website is under construction, related stock images and photos are used temporarily.

**Comment by FoamyGuy** [comment]
@DogushC okay, thank you. Lets wait until you've got photos of the device. You can commit them to this branch once the boards come.

**Comment by DogushC** [comment]
@FoamyGuy i have added real photos of our boards.

**Pull request merged**
