### PR TITLE
Added TinkeringTech's ScoutMakes Azul board information

### PR DESCRIPTION
**Pull request by tinkeringtech**
Added TinkeringTech's ScoutMakes Azul board information (images and .md) to circuitpython.org

### CODE REVIEW

**Comment by makermelissa** [comment]
I forgot to mention, the filename is very specific because it is decided by the script that generates the board information and is determined on how it was added to CircuitPython.

**Comment by tinkeringtech** [comment]
> I forgot to mention, the filename is very specific because it is decided by the script that generates the board information and is determined on how it was added to CircuitPython.

Thanks for taking a look. I proposed modifications to the existing file. Do I resubmit the pull request minus the .md file i.e just the images?

**Comment by makermelissa** [comment]
You can just update the existing file, remove the new one and push the changes in this PR. The items that you'll want to leave the same in the original file are: layout, board_id, and date_added. You can update whatever else.

**Comment by tinkeringtech** [comment]
@makermelissa I removed the .md file from my original PR. Submitted a change request to modify the existing page https://github.com/adafruit/circuitpython-org/blob/master/_board/tinkeringtech_scoutmakes_azul.md

Hope this makes sense. Thanks for your help.

**Comment by makermelissa** [comment]
I don't see the change request for the original file. Could you point me to it? Thanks

**Comment by tinkeringtech** [comment]
> I don't see the change request for the original file. Could you point me to it? Thanks

@makermelissa Sorry, I did not create a PR after I had submitted my changes earlier. Here is the patch for the existing .md file https://github.com/adafruit/circuitpython-org/pull/517 Hope it looks ok. I kept the parameters you mentioned above the same with others modified. This process was a good exercise to ensure my future board PR goes well :) Thanks.

**Pull request merged**
