### PR TITLE
Add missing boards for CP 8.2.9 plus more Adafruit links

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by makermelissa** [comment]
I generally try and change text like that, so I just updated it.

**Review by dhalbert — CHANGES_REQUESTED** [review]
wisdpi_tiny_rp2040.md needs a little copyediting to remove first-person references. It's also quite redundant: for instance the additional WS2812 RGB LED is mentioned three times (!).

I started to propose suggestions, but it got out of hand :)

**Comment by makermelissa** [comment]
Yeah, I had copied and pasted from their website. I just revised most of it and updated.

**Review by dhalbert — APPROVED** [review]
Thanks for cleanining up the copy.

**Comment by dhalbert** [comment]
The multiple links for boards is working out great! Thanks for adding that.

**Comment by makermelissa** [comment]
You're welcome. :)

**Pull request merged**
