### PR TITLE
Add Cedar Grove StringCar M0 Express to Downloads

### PR DESCRIPTION
**Pull request by CedarGroveStudios**

### CODE REVIEW

**Comment by CedarGroveStudios** [comment]
Will update renderings with photographs later.

**Comment by CedarGroveStudios** [comment]
How's this looking? Do I need to add or change anything?

**Comment by CedarGroveStudios** [comment]
Thank you, Melissa!

**Comment by makermelissa** [comment]
You're welcome!

**Comment by ptorrone** [comment]
nice work folks, added to newsletter, we're now up to 81 boards!

**Pull request merged**
