### PR TITLE
Waveshare esp32 s2 pico lcd

### PR DESCRIPTION
**Pull request by dglaude**
Basic adapted copy of the description for "Waveshare esp32 s2 pico WITHOUT lcd".
Images and additional information coming from https://www.waveshare.com/esp32-s2.htm

### CODE REVIEW

**Comment by makermelissa** [comment]
Thanks, but this was already done in #1027 which has been waiting on review for a couple of days now.

**Comment by makermelissa** [comment]
Closing this as a duplicate. The other PR is now merged. If you want to update any text on it, feel free.

**Comment by dglaude** [comment]
That's fine, it's great that there are no more "unknown" board thanks to #1027.

**Comment by makermelissa** [comment]
I do appreciate it when others add boards. It's unfortunate when duplicate work ends up being done because things sit though.

**Pull request closed without merging**
