### PR TITLE
Add mixgo CE board information

### PR DESCRIPTION
**Pull request by dahanzimin**
Thank circuitpython for adding a new board to circuitpython org. I hope it can pass

### CODE REVIEW

**Review by jepler — CHANGES_REQUESTED** [review]
For the `features:` portion of the board information, please only use the values listed in the template:
```
# Features are tags; they should be limited to the items in this list and spelled exactly the same.
# Include only the features your board supports, and remove these comment lines before committing.
# Breadboard-Friendly is a parallel pin layout with minimal non-critical perpendicular pins
features:
  - Speaker
  - Solder-Free Alligator Clip
  - Feather-Compatible
  - Battery Charging
  - Display
  - Wi-Fi
  - Bluetooth/BTLE
  - Robotics
  - LoRa/Radio
  - GPS
  - STEMMA QT/QWIIC
  - USB-C
  - Breadboard-Friendly
  - Arduino Shield Compatible
```

**Review by dahanzimin — COMMENTED** [review]
Modify features

**Comment by jepler** [comment]
Has this board been added to circuitpython? A board definition needs to be added to circuitpython first, then the board can be listed on circuitpython.org

**Comment by dahanzimin** [comment]
Thank you. I've submitted the application board at circuit python. Let's pass it later

**Comment by makermelissa** [comment]
Note: This is waiting on https://github.com/adafruit/circuitpython/pull/6383 to be merged first.

**Comment by dahanzimin** [comment]
@makermelissa  Thanks for your help and support. [adafruit/circuitpython#6383](https://github.com/adafruit/circuitpython/pull/6383)has been merged. The same board corresponds to different modes (circuit Python combines two boards). Here are also two pages to correspond. Thank you

**Comment by makermelissa** [comment]
Ok cool. One more request. I just noticed as I was giving this a final look over, your images are square. Could you adjust them so they are rectangular as described here: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/preparing-the-images

Otherwise this looks good. Thanks.

**Review by makermelissa — APPROVED** [review]
Looks great. Thank you.

**Pull request merged**
