### PR TITLE
Update docs for VINA-D51

### PR DESCRIPTION
**Pull request by fabaff**
- Spec were moved down and synced with vendor page
- Links
- Update formatting of list to improve readability

CC @bd34n

### CODE REVIEW

**Comment by ladyada** [comment]
hmm why was the text that the board is unavailable added?
https://bdmicro.com/products/vina-d51

**Comment by fabaff** [comment]
The "VINA-D21" can't be found anymore. The URL is 404, thus it looks like that this board was discontinued and replaced by "VINA-D51".

I tagged @bd34n who is the owner of BDMICRO LLC to be sure.

**Comment by makermelissa** [comment]
You could just remove the purchase section altogether since the board isn't available. That's what I usually do for boards without a purchase link.

**Comment by fabaff** [comment]
> You could just remove the purchase section altogether since the board isn't available.

Section removed.

**Review by makermelissa — APPROVED** [review]
Looks good. Thanks.

**Comment by bd34n** [comment]
@fabaff, @makermelissa, my sincere apologies I missed this while it was happening. Yes - VINA-D21 is no longer for sale. VINA-D51 has always been a separate product, so it is not a replacement. And I apologies for not making these updates myself. :-(

Thank you!

**Comment by fabaff** [comment]
@bd34n, thanks for the clarification.

**Pull request merged**
