### PR TITLE
Updated Design - header, mobile menu and landing page

### PR DESCRIPTION
**Pull request by jwcooper**
Updates header, mobile menu, and landing page based on latest designs from @tylerdcooper.

### CODE REVIEW

**Comment by tannewt** [comment]
Is there anywhere we can preview this? @kattni and @makermelissa would be interested as well.

**Comment by makermelissa** [comment]
@tannewt, I should be able to run it locally. I'm not sure about a preview site though.

**Comment by makermelissa** [comment]
I just previewed. It looks very nice and I everything appeared to function nicely.

**Comment by jwcooper** [comment]
@tannewt sent you a link to my ngrok.

**Pull request merged**
