### PR TITLE
Adding family of Pykey boards

### PR DESCRIPTION
**Pull request by jpconstantineau**
Adding md files for 3 new boards.
Still need to update pictures and store links.
I turned-off the downloads to a couple as they are not ready on Tindie yet,

### CODE REVIEW

**Comment by makermelissa** [comment]
Hi, let's leave this open until you add some pics. Even something quick like a board layout as a placeholder would work for now.

**Review by makermelissa — DISMISSED** [review]
Requesting some photos to be added.

**Comment by jpconstantineau** [comment]
I just added the pictures and updated the store links.  Some of them might not be "live" as they are still drafts on Tindie.  These are left as `downloads_display: false` for now.

**Comment by jpconstantineau** [comment]
All pictures were added.  Anything else needs updating before merging in?

**Pull request merged**
