### PR TITLE
Updated ShIRtty board photo

### PR DESCRIPTION
**Pull request by makermelissa**
Author provided a better photo.

### CODE REVIEW

**Comment by ladyada** [comment]
do you need all 3 sizes?

**Comment by makermelissa** [comment]
Unless something has changed, that my understanding was that all 3 were supposed to be provided. The large one is used when you are viewing the board details, the small one is used on the screen that displays all the boards and the original is supposed to be used as a fallback if the other images aren't available.

**Comment by makermelissa** [comment]
We could probably get away with adding the large and small only at this point in time. It would be nice if there were automatic resizing and caching of the resized images.

**Comment by ladyada** [comment]
oh wait i see the diff doesnt remove the files - it looked like they were deleted...all good!

**Pull request merged**
